server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: booking_schema
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: booking_schema
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root

  redis:
    host: localhost
    port: 6379

unit:
  markup-percentage: 0.15