version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: booking_redis
    ports:
      - "6379:6379"